version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ride_hailing_postgres
    environment:
      POSTGRES_USER: ride_hailing
      POSTGRES_PASSWORD: ride_hailing_password
      POSTGRES_DB: ride_hailing
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ride_hailing_redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
